# Generated by Django 5.1.1 on 2024-09-19 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobio', '0006_userprofile_email_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('in_progress', 'In Progress')], default='Pending', max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('measurements', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobio.userprofile')),
                ('customization_options', models.ManyToManyField(blank=True, to='biobio.customizationoption')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
