# Generated by Django 5.1.1 on 2024-09-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobio', '0007_customizationoption_order_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(max_length=100),
        ),
    ]
