# Generated by Django 5.1.1 on 2024-10-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobio', '0011_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='order',
            field=models.CharField(max_length=100),
        ),
    ]
