# Generated by Django 5.1.1 on 2024-10-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobio', '0012_alter_notificationlog_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='material',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_Color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
